apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresport
      protocol: TCP
      name: postgresport
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
